[package]
name = "oracle_service"
version = "0.0.0"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives", subdir = "initia_stdlib", rev = "main" }

[addresses]
std =  "0x1"
oracle_service= "0x960BB17905E1DC5298F7E3A9051681957463A577"